"""
StableShield AI - Supabase Type Generator
Regenerates apps/web/types/database.types.ts from the live Supabase
schema, replacing the hand-authored mirror used during early
development.

Prerequisites:
  npm install -g supabase
  supabase login
  supabase link --project-ref <your-project-ref>

Usage:
  python scripts/generate_supabase_types.py --project-ref abcdefghijklmnop
"""

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = ROOT / "apps" / "web" / "types" / "database.types.ts"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Supabase TypeScript types")
    parser.add_argument("--project-ref", required=True, help="Supabase project ref")
    args = parser.parse_args()

    cmd = ["supabase", "gen", "types", "typescript", "--project-id", args.project_ref]
    print(f"Running: {' '.join(cmd)}")

    result = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        return 1

    header = (
        "// Auto-generated by scripts/generate_supabase_types.py via "
        "`supabase gen types typescript`. Do not hand-edit - re-run the\n"
        "// script after any migration change instead.\n"
    )
    OUTPUT_PATH.write_text(header + result.stdout, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
